export enum emailEnum {
	DISPLAY_FLIGHT = 4,
	DISPLAY_WOOLWORTHS = 5,
	DISPLAY_RED_ENERGY = 6,
	DISPLAY_UBER = 7,
	DISPLAY_HOYTS = 8,
	DISPLAY_CREDIT_CARDS = 9,
	DISPLAY_SHOPPING = 10,
	DISPLAY_WELLNESS = 11,
	DISPLAY_HOTELS = 12,
	DISPLAY_INSURANCE = 13,
	DISPLAY_TRAVEL_MONEY = 14
}