branch-defaults:
  aws-ebs:
    environment: masesays-api
    group_suffix: null
  master:
    environment: node-express-env
environment-defaults:
  node-express-env:
    branch: master
    repository: origin
global:
  application_name: my-be
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
